name: Pickle Compatibility Test

on: [push, pull_request]

jobs:
  generate_pickles:
    name: Generate Pickles (${{ matrix.os }}, Python ${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.8", "3.9", "3.10", "3.11"]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install tqdm

      - name: Test and generate pickle file
        run: python test_pickle.py

      - name: Upload pickle file
        uses: actions/upload-artifact@v4
        with:
          name: pickle_py${{ matrix.python }}_${{ matrix.os }}.pickle
          path: pickle_py${{ matrix.python }}_${{ matrix.os }}.pickle

  compare_pickles:
    name: Compare Pickles
    needs: generate_pickles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all pickles
        uses: actions/download-artifact@v4
        with:
          path: pickles/
          merge-multiple: true
      - name: Compare pickles
        run: |
          mv pickles/*.txt ./
          ls ./
          python compare_pickles.py
